import type { Metadata } from "next";
import PageHero from "@/components/PageHero";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Learn how FundCo Capital Managers collects, uses, and protects your personal data when you use our website, and how the law protects your privacy rights.",
};

function P({ children }: { children: React.ReactNode }) {
  return <p className="text-text-secondary leading-relaxed mb-4">{children}</p>;
}

function H2({ children }: { children: React.ReactNode }) {
  return <h2 className="text-xl font-bold text-brand mt-8 mb-3">{children}</h2>;
}

function H3({ children }: { children: React.ReactNode }) {
  return <h3 className="font-semibold text-text mt-4 mb-2">{children}</h3>;
}

export default function PrivacyPolicy() {
  return (
    <>
      <PageHero title="Privacy Policy" subtitle="Last updated: July 14, 2021" />

      <section className="mx-auto max-w-3xl px-6 py-16">
        <P>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use
          the Service and tells You about Your privacy rights and how the
          law protects You.
        </P>
        <P>
          We use Your Personal data to provide and improve the Service. By
          using the Service, You agree to the collection and use of
          information in accordance with this Privacy Policy.
        </P>

        <H2>Interpretation and Definitions</H2>
        <H3>Interpretation</H3>
        <P>
          The words in which the initial letter is capitalized have
          meanings defined under the following conditions. The following
          definitions shall have the same meaning regardless of whether
          they appear in singular or in the plural.
        </P>

        <H3>Definitions</H3>
        <P>For the purposes of this Privacy Policy:</P>
        <ul className="list-disc pl-6 space-y-2 text-text-secondary mb-4">
          <li>
            <strong>Account</strong> means a unique account created for You
            to access our Service or parts of our Service.
          </li>
          <li>
            <strong>Company</strong> (referred to as either &ldquo;the
            Company&rdquo;, &ldquo;We&rdquo;, &ldquo;Us&rdquo; or
            &ldquo;Our&rdquo; in this Agreement) refers to FundCo, Lagos,
            Nigeria.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on
            Your computer, mobile device or any other device by a website,
            containing the details of Your browsing history on that
            website among its many uses.
          </li>
          <li>
            <strong>Country</strong> refers to Nigeria.
          </li>
          <li>
            <strong>Device</strong> means any device that can access the
            Service such as a computer, a cellphone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates
            to an identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal
            person who processes the data on behalf of the Company.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected
            automatically, either generated by the use of the Service or
            from the Service infrastructure itself.
          </li>
          <li>
            <strong>Website</strong> refers to FundCo, accessible from
            fundco.ng
          </li>
          <li>
            <strong>You</strong> mean the individual accessing or using the
            Service, or the company, or other legal entity on behalf of
            which such individual is accessing or using the Service, as
            applicable.
          </li>
        </ul>

        <H2>Collecting and Using Your Personal Data</H2>
        <H3>Types of Data Collected</H3>
        <p className="font-medium text-text mb-1">Personal Data</p>
        <P>
          While using Our Service, We may ask You to provide Us with
          certain personally identifiable information that can be used to
          contact or identify You. Personally identifiable information may
          include, but is not limited to: Email address.
        </P>

        <p className="font-medium text-text mb-1">Usage Data</p>
        <P>Usage Data is collected automatically when using the Service.</P>
        <P>
          Usage Data may include information such as Your Device&rsquo;s
          Internet Protocol address (e.g. IP address), browser type,
          browser version, the pages of our Service that You visit, the
          time and date of Your visit, the time spent on those pages,
          unique device identifiers and other diagnostic data.
        </P>

        <H3>Tracking Technologies and Cookies</H3>
        <P>
          We use cookies and similar tracking technologies to track the
          activity on Our Service and store certain information. We use
          both Session and Persistent Cookies for the purposes set out
          below: Necessary/Essential Cookies, Cookies Policy/Notice
          Acceptance Cookies, and Functionality Cookies.
        </P>

        <H2>Use of Your Personal Data</H2>
        <P>The Company may use Personal Data for the following purposes:</P>
        <ul className="list-disc pl-6 space-y-2 text-text-secondary mb-4">
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage Your Account and provide access to different functionalities of the Service.</li>
          <li>For the performance of a contract for the products, items or services You have purchased.</li>
          <li>To contact You by email, telephone, SMS, or other equivalent forms of electronic communication.</li>
          <li>To provide You with news, special offers and general information about similar goods and services.</li>
          <li>To manage Your requests to Us.</li>
          <li>For business transfers, such as a merger, divestiture, or restructuring.</li>
          <li>For other purposes, such as data analysis and improving our Service.</li>
        </ul>

        <H2>Retention of Your Personal Data</H2>
        <P>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy, and to
          comply with our legal obligations, resolve disputes, and enforce
          our legal agreements and policies.
        </P>

        <H2>Transfer of Your Personal Data</H2>
        <P>
          Your information, including Personal Data, is processed at the
          Company&rsquo;s operating offices and in any other places where
          the parties involved in the processing are located.
        </P>

        <H2>Disclosure of Your Personal Data</H2>
        <P>
          The Company may disclose Your Personal Data in connection with a
          business transaction, if required by law, or in the good faith
          belief that such action is necessary to comply with a legal
          obligation or protect the rights and safety of the Company or
          others.
        </P>

        <H2>Security of Your Personal Data</H2>
        <P>
          The security of Your Personal Data is important to Us, but
          remember that no method of transmission over the Internet, or
          method of electronic storage is 100% secure. While We strive to
          use commercially acceptable means to protect Your Personal Data,
          We cannot guarantee its absolute security.
        </P>

        <H2>Children&rsquo;s Privacy</H2>
        <P>
          Our Service does not address anyone under the age of 13. We do
          not knowingly collect personally identifiable information from
          anyone under the age of 13.
        </P>

        <H2>Links to Other Websites</H2>
        <P>
          Our Service may contain links to other websites that are not
          operated by Us. We strongly advise You to review the Privacy
          Policy of every site You visit.
        </P>

        <H2>Changes to this Privacy Policy</H2>
        <P>
          We may update Our Privacy Policy from time to time. We will
          notify You of any changes by posting the new Privacy Policy on
          this page and updating the &ldquo;Last updated&rdquo; date.
        </P>

        <H2>Contact Us</H2>
        <P>
          If you have any questions about this Privacy Policy, You can
          contact us by email at{" "}
          <a href="mailto:info@fundco.ng" className="text-brand">
            info@fundco.ng
          </a>
        </P>
      </section>
    </>
  );
}
